### ISSUE TITLE
Couldn't find preset "react"

### ISSUE THREAD

**Issue by proov** [stutrek/scrollmonitor-parallax#6]
Hello,

I installed both scripts `scrollmonitor` and `scrollmonitor-parallax` with npm.

I get this error : 
```shell
  0:0  error  Module build failed: Error: Couldn't find preset "react" relative to
              directory
              "/Users/sylvainprevost/Sites/wp-starter/front/node_modules/scrollmonitor-parallax"

✖ 1 problem (1 error, 0 warnings)

webpack: Failed to compile.
```

I tried this :
```
import scrollMonitor from 'scrollmonitor';
import Parallax from 'scrollmonitor-parallax';
```
and 
```
import scrollMonitor from 'scrollmonitor/scrollMonitor.js';
import Parallax from 'scrollmonitor-parallax/Components.js';
```

None of these works. ScrollMonitor works fine, but Parallax extention not :(

**Comment by stutrek** [comment]
Are you using the latest version?

**Comment by proov** [comment]
i think so,

```json
"scrollmonitor": "^1.2.4",
"scrollmonitor-parallax": "^1.1.1",
```

**Comment by stutrek** [comment]
Can you have your babel loader skip files in node_modules?

**Comment by proov** [comment]
I think it's caused by my module bundler config. I tried on an another project based on Nuxt.js, it works fine. 

I just checked my webpack config, i see `//exclude: /node_modules/,`... I'm gonna uncomment this line and try it tomorow ^^ Thanks !

**Comment by stutrek** [comment]
Closing because I'm assuming you got it working

**Comment by proov** [comment]
Working perfectly, thanks a lot @stutrek  !
